name: CI
on: push

env:
  NODE_VERSION: 16

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Instrall Node
      uses: actions/checkout@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install modules
      run: npm ci

    - name: Run linting
      run: npm run lint
